In [46]:
"""
Function
--------
simulate_prizedoor

Generate a random array of 0s, 1s, and 2s, representing
hiding a prize between door 0, door 1, and door 2

Parameters
----------
nsim : int
    The number of simulations to run

Returns
-------
sims : array
    Random array of 0s, 1s, and 2s

Example
-------
>>> print simulate_prizedoor(3)
array([0, 0, 2])
"""

def simulate_prizedoor(nsim):
    import numpy as np 
    import numpy.matlib
    answer = np.random.randint(3,size=nsim)
    #answer=answer*2.4999999
    #answer=np.round(answer)
    return answer
#your code here

In [61]:
simulate_prizedoor(100)

array([2, 2, 2, 2, 2, 1, 2, 1, 0, 2, 2, 1, 2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 2,
       1, 0, 2, 0, 2, 2, 1, 0, 2, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 1, 0, 0, 2,
       1, 0, 0, 2, 2, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 2, 0, 0, 0, 2, 0, 2,
       0, 1, 1, 1, 2, 1, 1, 2, 0, 1, 1, 1, 0, 0, 1, 2, 2, 2, 2, 2, 1, 0, 1,
       2, 1, 0, 0, 0, 2, 0, 1])

In [48]:

"""
Function
--------
simulate_guess

Return any strategy for guessing which door a prize is behind. This
could be a random strategy, one that always guesses 2, whatever.

Parameters
----------
nsim : int
    The number of simulations to generate guesses for

Returns
-------
guesses : array
    An array of guesses. Each guess is a 0, 1, or 2

Example
-------
>>> print simulate_guess(5)
array([0, 0, 0, 0, 0])
"""
def simulate_guess(nsim):
    import numpy as np 
    import numpy.matlib
    answer = np.random.randint(3,size=nsim)
    return answer

In [79]:
"""
Function
--------
goat_door

Simulate the opening of a "goat door" that doesn't contain the prize,
and is different from the contestants guess

Parameters
----------
prizedoors : array
    The door that the prize is behind in each simulation
guesses : array
    THe door that the contestant guessed in each simulation

Returns
-------
goats : array
    The goat door that is opened for each simulation. Each item is 0, 1, or 2, and is different
    from both prizedoors and guesses

Examples
--------
>>> print goat_door(np.array([0, 1, 2]), np.array([1, 1, 1]))
>>> array([2, 2, 0])
"""
def goat_door(prizedoors,guesses):
    answer=[]
    if(not len(prizedoors)==len(guesses)):
        return "Error: The arrays are of two different sizes"
    else:
        for x in range(0,len(prizedoors)):
            if(prizedoors[x]==guesses[x]):
                if(prizedoors[x]==0):
                    answer.append(1)
                if(prizedoors[x]==1):
                    answer.append(2)
                if(prizedoors[x]==2):
                    answer.append(0)
            else:
                if(prizedoors[x]+guesses[x]==3):
                    answer.append(0)
                elif(prizedoors[x]+guesses[x]==1):
                    answer.append(2)
                elif(prizedoors[x]+guesses[x]==2):
                    answer.append(1)
        return answer
                    
    

In [80]:
goat_door(simulate_prizedoor(100),simulate_guess(100))

[2,
 0,
 2,
 2,
 0,
 1,
 1,
 0,
 2,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 2,
 2,
 1,
 1,
 0,
 0,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 2,
 0,
 1,
 1,
 0,
 1,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 1,
 2,
 0,
 0,
 1,
 1,
 2,
 1,
 2,
 0,
 0,
 1,
 2,
 2,
 2,
 0,
 1,
 2,
 2,
 2,
 0,
 2,
 2,
 2,
 1,
 2,
 1,
 1,
 2,
 2,
 0,
 2,
 1,
 2,
 0,
 2,
 2,
 0,
 0,
 2,
 2,
 2,
 0,
 0,
 0,
 0,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1]

In [81]:
simulate_guess(100)

array([0, 2, 1, 0, 0, 2, 0, 1, 0, 0, 0, 2, 1, 2, 0, 1, 2, 1, 2, 0, 2, 2, 1,
       0, 2, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0, 0, 2, 1, 0, 1, 1, 1, 0, 2, 0, 1,
       0, 0, 2, 2, 0, 1, 1, 2, 1, 0, 0, 2, 2, 2, 1, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 2, 0, 0, 2, 1, 1, 0, 2, 1, 2, 1, 2, 1, 2, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 2, 1, 1, 2, 1, 1, 0])

In [82]:
goat_door([2, 2, 2, 2, 2, 1, 2, 1, 0, 2, 2, 1, 2, 1, 0, 0, 1, 0, 2, 2, 1, 1, 2,
       1, 0, 2, 0, 2, 2, 1, 0, 2, 1, 2, 1, 2, 2, 1, 0, 1, 0, 1, 1, 0, 0, 2,
       1, 0, 0, 2, 2, 0, 1, 1, 1, 0, 1, 1, 1, 2, 0, 1, 2, 0, 0, 0, 2, 0, 2,
       0, 1, 1, 1, 2, 1, 1, 2, 0, 1, 1, 1, 0, 0, 1, 2, 2, 2, 2, 2, 1, 0, 1,
       2, 1, 0, 0, 0, 2, 0, 1],[2, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0, 1, 2, 0,
       1, 0, 2, 1, 2, 0, 1, 0, 2, 2, 2, 2, 0, 0, 0, 1, 1, 0, 2, 1, 2, 1, 2,
       0, 2, 2, 0, 1, 1, 0, 2, 1, 1, 1, 0, 2, 0, 0, 2, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 2, 0, 0, 1, 0, 0, 0, 2, 2, 0, 0, 0, 1, 1, 2, 0, 1, 0, 1, 2, 0,
       1, 1, 2, 1, 2, 1, 1, 1])

[0,
 0,
 1,
 1,
 0,
 2,
 1,
 2,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 2,
 1,
 0,
 1,
 2,
 0,
 1,
 2,
 1,
 0,
 2,
 0,
 1,
 2,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 2,
 2,
 2,
 1,
 0,
 2,
 1,
 2,
 0,
 2,
 1,
 1,
 1,
 0,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 0,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 0,
 1,
 0,
 1,
 2,
 0,
 2,
 1,
 2,
 2,
 1,
 1,
 0,
 0,
 2,
 1,
 1,
 2,
 0,
 0,
 1,
 0,
 1,
 2,
 1,
 2,
 0,
 2,
 1,
 2,
 1,
 0,
 2,
 2]

In [83]:
"""
Function
--------
switch_guess

The strategy that always switches a guess after the goat door is opened

Parameters
----------
guesses : array
     Array of original guesses, for each simulation
goatdoors : array
     Array of revealed goat doors for each simulation

Returns
-------
The new door after switching. Should be different from both guesses and goatdoors

Examples
--------
>>> print switch_guess(np.array([0, 1, 2]), np.array([1, 2, 1]))
>>> array([2, 0, 0])
"""
def switch_guess(guesses,goatdoors):
    answer=[]
    if(not (len(guesses)==len(goatdoors))):
        return "Error in the length of the array"
    else:
        for x in range(0,len(guesses)):
            if(guesses[x]+goatdoors[x]==1):
                answer.append(2)
            elif(guesses[x]+goatdoors[x]==2):
                answer.append(1)
            elif(guesses[x]+goatdoors[x]==3):
                answer.append(0)
            else:
                answer.append(99)
        return answer

In [86]:
guesses=simulate_guess(100)
goatdoors=goat_door(simulate_prizedoor(100),guesses)
print(guesses)
print(goatdoors)
switch_guess(guesses,goatdoors)

[1 1 2 1 1 1 1 0 0 0 1 2 0 2 0 1 2 1 2 0 1 1 0 2 2 2 1 2 0 0 2 1 0 1 1 0 0
 0 0 2 0 1 2 1 0 0 1 2 2 2 1 2 2 0 0 0 2 1 0 0 2 0 0 0 2 0 2 2 2 0 2 2 1 2
 0 2 1 1 1 2 0 0 2 0 1 2 1 1 1 0 1 1 0 1 0 0 1 1 1 1]
[0, 2, 1, 0, 2, 0, 0, 1, 2, 2, 0, 1, 2, 1, 1, 2, 0, 0, 1, 1, 0, 2, 1, 0, 1, 0, 2, 0, 1, 1, 0, 0, 2, 0, 0, 2, 2, 2, 1, 0, 1, 2, 0, 2, 1, 1, 2, 0, 0, 0, 2, 0, 1, 1, 2, 1, 1, 0, 2, 1, 0, 1, 1, 2, 1, 2, 0, 1, 1, 2, 1, 0, 0, 1, 2, 1, 0, 0, 2, 1, 2, 1, 0, 1, 2, 0, 2, 2, 2, 1, 0, 2, 1, 0, 1, 1, 0, 2, 2, 2]


[2,
 0,
 0,
 2,
 0,
 2,
 2,
 2,
 1,
 1,
 2,
 0,
 1,
 0,
 2,
 0,
 1,
 2,
 0,
 2,
 2,
 0,
 2,
 1,
 0,
 1,
 0,
 1,
 2,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 1,
 2,
 0,
 1,
 0,
 2,
 2,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 2,
 1,
 2,
 0,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 2,
 0,
 1,
 0,
 2,
 2,
 0,
 0,
 1,
 2,
 1,
 2,
 0,
 1,
 0,
 0,
 0,
 2,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0,
 0]

In [89]:
"""
Function
--------
win_percentage

Calculate the percent of times that a simulation of guesses is correct

Parameters
-----------
guesses : array
    Guesses for each simulation
prizedoors : array
    Location of prize for each simulation

Returns
--------
percentage : number between 0 and 100
    The win percentage

Examples
---------
>>> print win_percentage(np.array([0, 1, 2]), np.array([0, 0, 0]))
33.333
"""
def win_percentage(guesses,prizedoors):
    correctguesses=0
    if(not(len(guesses)==len(prizedoors))):
        return "Error in the length of the arrays"
    else:
        for x in range(0,len(guesses)):
            if(guesses[x]==prizedoors[x]):
                correctguesses+=1
        return (correctguesses/len(guesses))*100

In [99]:
guesses=simulate_guess(10000000)
prizedoors=simulate_prizedoor(10000000)
goatdoors=goat_door(prizedoors,guesses)
print('if you decide to switch doors your percentage change of winning is:')
print(win_percentage(switch_guess(guesses,goatdoors),prizedoors))
print('if you decide to stick with the original door you chance of winninig is:')
print(win_percentage(guesses,prizedoors))

if you decide to switch doors your percentage change of winning is:
66.66977
if you decide to stick with the original door you chance of winninig is:
33.33023
