In [1]:
import pandas as pd
import numpy as np


In [26]:
x=np.empty([3,2],dtype=int)
print(x)

[[0 0]
 [0 0]
 [0 0]]


In [27]:
x=[1,2,4]
a=np.asarray(x)
print(a)

[1 2 4]


In [30]:
x=[1,2,3]
a=np.asarray(x,dtype=float)
print(a)

[ 1.  2.  3.]


In [35]:
formula = "K4(ON(SO3)2)2"
class Solution:
    def countOfAtoms(self, formula):
        elements={};
        parentheses=0;
        for i in range(0,len(formula)-1):
             if(formula[i].isupper()):
                  element=formula[i];
                  if(formula[i+1].islower()):
                       element+=formula[i+1];
             elif(formula[i]=='/('):
                       parentheses+=1;
             elif(formula[i]=='/)'):
                       parentheses-=1;

                       

In [36]:
x=(1,2,3)
a=np.asarray(x)
print(a)

[1 2 3]


In [37]:
x=[(1,2,4),(3,7)]
a=np.asarray(x)
print(a)

[(1, 2, 4) (3, 7)]


In [41]:
s="Hello World"
a=np.frombuffer(s,dtype='S1')
print(a)

AttributeError: 'str' object has no attribute '__buffer__'

In [43]:
lst=range(5)
print(lst)

range(0, 5)


In [44]:
lst=range(5)
it=iter(lst)
x=np.fromiter(it,dtype=float)
print(x)

[ 0.  1.  2.  3.  4.]


In [45]:
x=np.arange(5,dtype=float)
print(x)

[ 0.  1.  2.  3.  4.]


In [46]:
x=np.arange(10,20,2)
print(x)

[10 12 14 16 18]


In [47]:
x=np.linspace(10,20,5)
print(x)

[ 10.   12.5  15.   17.5  20. ]


In [48]:
x=np.linspace(10,20,5,endpoint=False)
print(x)

[ 10.  12.  14.  16.  18.]


In [50]:
x=np.linspace(1,2,5,retstep=True)
print(x)

(array([ 1.  ,  1.25,  1.5 ,  1.75,  2.  ]), 0.25)


In [51]:
x=np.logspace(1.0,2.0, num=10)
print(x)

[  10.           12.91549665   16.68100537   21.5443469    27.82559402
   35.93813664   46.41588834   59.94842503   77.42636827  100.        ]


In [53]:
a=np.logspace(1,10,num=10,base=2)
print(a)

[    2.     4.     8.    16.    32.    64.   128.   256.   512.  1024.]


In [54]:
a=np.arange(10)
s=slice(2,7,2)
print(a)
print(a[s])

[0 1 2 3 4 5 6 7 8 9]
[2 4 6]


In [55]:
a=np.arange(10)
b=a[2:7:2]
print(b)

[2 4 6]


In [56]:
a=np.arange(10)
b=a[5]
print(b)

5


In [57]:
a=np.arange(10)
b=a[5:]
print(b)

[5 6 7 8 9]


In [58]:
a=np.arange(10)
b=a[2:4]
print(b)

[2 3]


In [59]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6]
 [7 8 9]]


In [61]:
a=np.array([[1,2,3],[3,4,6],[4,5,6]])
print(a)

[[1 2 3]
 [3 4 6]
 [4 5 6]]


In [62]:
print(a[...,1])

[2 4 5]


In [63]:
print(a[1,...])

[3 4 6]


In [64]:
print(a[...,1:])

[[2 3]
 [4 6]
 [5 6]]


In [65]:
x=np.array([[1,2],[3,4],[5,6]])
y=x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]


In [3]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print(x)
rows=np.array([[0,0],[3,3]])
cols=np.array([[0,2],[0,2]])
y=x[rows,cols]
print(y)
#this seems strang to me

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  2]
 [ 9 11]]


In [4]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Our array is:')
print(x)
print('\n')

#slicing
z=x[1:4,1:3]
print('after slicing the array becomes')
print(z)
print('\n')

#using advanced index for column
y=x[1:4,[1,2]]

print('slicing using advanced index for columns:')
print(y)

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


after slicing the array becomes
[[ 4  5]
 [ 7  8]
 [10 11]]


slicing using advanced index for columns:
[[ 4  5]
 [ 7  8]
 [10 11]]


In [5]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
print('Our array is:')
print(x)
print('\n')

#Now we will print the items greater the 5
print('the items greater the 5 are:')
print(x[x>5])

Our array is:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


the items greater the 5 are:
[ 6  7  8  9 10 11]


In [3]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
print(a[~np.isnan(a)])

[ 1.  2.  3.  4.  5.]


In [4]:
a = np.array([1, 2+6j, 5, 3.5+5j]) 
print(a[np.iscomplex(a)])

[ 2.0+6.j  3.5+5.j]


In [6]:
a=np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b=np.array([1.0,2.0,3.0])

print('the first array is:')
print(a)
print('\n')

print('the second array is:')
print(b)
print('\n')

print('first array+second array')
print(a+b)

the first array is:
[[  0.   0.   0.]
 [ 10.  10.  10.]
 [ 20.  20.  20.]
 [ 30.  30.  30.]]


the second array is:
[ 1.  2.  3.]


first array+second array
[[  1.   2.   3.]
 [ 11.  12.  13.]
 [ 21.  22.  23.]
 [ 31.  32.  33.]]


In [9]:
a=np.arange(0,60,5)
a=a.reshape(3,4)
print('the oringinal array is:')
print(a)
print('\n')

print ('the modified arrray is:')
for x in np.nditer(a):
    print(x,)

the oringinal array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


the modified arrray is:
0
5
10
15
20
25
30
35
40
45
50
55


In [11]:
a=np.arange(0,60,5)
a=a.reshape(3,4)

print('the original array is:')
print(a)
print('\n')

print('the transpose of the array is:')
b=a.T
print(b)
print('\n')

print('the modified array is:')
for x in np.nditer(b):
    print( x,)

the original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


the transpose of the array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


the modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [12]:
a=np.arange(0,60,5)
a=a.reshape(3,4)
print('the oringinal array is:')
print(a)
print('\n')

print('the transpose of the original array is:')
b=a.T
print(b)
print('\n')

print('sorted in c-style')
c=b.copy(order='C')
print(c)
for x in np.nditer(c):
    print(x,)

print('\n')

print('sorted in f-style')
d=b.copy(order='F')
print(d)
for x in np.nditer(d):
    print(x,)
    

the oringinal array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


the transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


sorted in c-style
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


sorted in f-style
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [13]:
a=np.arange(0,60,5)
a=a.reshape(3,4)

print('the orginal array is:')
print(a)
print('\n')

print('sorted in c-style')
for x in np.nditer(a,order='C'):
    print(x,)
print('\n')

print('sorted in f-style')
for x in np.nditer(a,order='F'):
    print(x,)


the orginal array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


sorted in c-style
0
5
10
15
20
25
30
35
40
45
50
55


sorted in f-style
0
20
40
5
25
45
10
30
50
15
35
55


In [3]:
a=np.arange(0,60,5)
a=a.reshape(3,4)
print('Original array is:')
print(a)
print('\n')

for x in np.nditer(a, op_flags=['readwrite']):
    x[...]=2*x
print('Modified array is:')
print(a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


In [3]:
import numpy as np 
a = np.arange(0,60,5)
a=a.reshape(3,4)
print('the original array is:')
print(a)
print('\n')
print('the modified array is:')
for x in np.nditer(a,flags=['external_loop'],order ='F'):
    print(x)

the original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


the modified array is:
[ 0 20 40]
[ 5 25 45]
[10 30 50]
[15 35 55]


In [4]:
a.T

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [6]:
import numpy as np
a = np.arange(0,60,5)
a=a.reshape(3,4)
print('Our firs array is:')
print(a)
print('\n')
print('Our second array is:')
b=np.array([1,2,3,4],dtype=int)
print(b)
print('\n')
print('The modifed array is:')
for x,y in np.nditer([a,b]):
    print('%d:%d'%(x,y),)

Our firs array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Our second array is:
[1 2 3 4]


The modifed array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


In [7]:
import numpy as np
print(np.__version__)

1.11.3


In [8]:
np.show_config()

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 